USE MoviesDB;
/*INSERT INTO Reviews VALUES (1, 'The Ring', 71, 7.1, 57)
INSERT INTO Reviews VALUES (2, 'A Quiet Place', 96, 7.5, 82)
INSERT INTO Reviews VALUES (3, 'Avengers:End Game', 94, 8.4, 78)
INSERT INTO Reviews VALUES (4, 'Monty Python and the Holy Grail', 97, 8.2, 91)
INSERT INTO Reviews VALUES (5, 'Spirited Away', 97, 8.6, 96)
INSERT INTO Reviews VALUES (6, 'Titanic', 89, 7.8, 75)
INSERT INTO Reviews VALUES (7, 'The Departed', 91, 8.5, 85)
INSERT INTO Reviews VALUES (8, 'Parasite', 98, 8.6, 96)

INSERT INTO Genre VALUES (1, 'Action')
INSERT INTO Genre VALUES (2, 'Adventure')
INSERT INTO Genre VALUES (3, 'Comedy')
INSERT INTO Genre VALUES (4, 'Dark Comedy')
INSERT INTO Genre VALUES (5, 'Documentary')
INSERT INTO Genre VALUES (6, 'Drama')
INSERT INTO Genre VALUES (7, 'Fantasy')
INSERT INTO Genre VALUES (8, 'Horror')
INSERT INTO Genre VALUES (9, 'Mystery')
INSERT INTO Genre VALUES (10, 'Romance')
INSERT INTO Genre VALUES (11, 'Romantic Comedy')
INSERT INTO Genre VALUES (12, 'Science Fiction')
INSERT INTO Genre VALUES (13, 'Thriller')

INSERT INTO Rating VALUES (1, 'PG')
INSERT INTO Rating VALUES (2, 'PG-13')
INSERT INTO Rating VALUES (3, 'R')
INSERT INTO Rating VALUES (4, 'NR')
INSERT INTO Rating VALUES (5, 'G')

INSERT INTO People VALUES (1, 'Alan Silvestri')
INSERT INTO People VALUES (2, 'Anthony Mackie')
INSERT INTO People VALUES (3, 'Anthony Russo')
INSERT INTO People VALUES (4, 'Bong Joon-ho')
INSERT INTO People VALUES (5, 'Brie Larson')
INSERT INTO People VALUES (6, 'Bryan Woods')
INSERT INTO People VALUES (7, 'Chadwick Boseman')
INSERT INTO People VALUES (8, 'Cho Yeo-jeong')
INSERT INTO People VALUES (9, 'Chris Evans')
INSERT INTO People VALUES (10, 'Chris Hemsworth')
INSERT INTO People VALUES (11, 'Christoper Markus')
INSERT INTO People VALUES (12, 'Daveigh Chase')
INSERT INTO People VALUES (13, 'David Dorfman')
INSERT INTO People VALUES (14, 'Dewolfe')
INSERT INTO People VALUES (15, 'Don Cheadle')
INSERT INTO People VALUES (16, 'Ehren Kruger')
INSERT INTO People VALUES (17, 'Elizabeth Olson')
INSERT INTO People VALUES (18, 'Emily Blunt')
INSERT INTO People VALUES (19, 'Eric Idle')
INSERT INTO People VALUES (20, 'Gore Verbinski')
INSERT INTO People VALUES (21, 'Graham Chapman')
INSERT INTO People VALUES (22, 'Hans Zimmer')
INSERT INTO People VALUES (23, 'Hayao Miyazaki')
INSERT INTO People VALUES (24, 'Howard Shore')
INSERT INTO People VALUES (25, 'Jack Nicholson')
INSERT INTO People VALUES (26, 'James Cameron')
INSERT INTO People VALUES (27, 'James Horner')
INSERT INTO People VALUES (28, 'Jeong Ji-so')
INSERT INTO People VALUES (29, 'Jeremy Renner')
INSERT INTO People VALUES (30, 'Joe Hisaishi')
INSERT INTO People VALUES (31, 'Joe Russo')
INSERT INTO People VALUES (32, 'John Cleese')
INSERT INTO People VALUES (33, 'John Krasinski')
INSERT INTO People VALUES (34, 'Jung Jae-il')
INSERT INTO People VALUES (35, 'Kate Winslet')
INSERT INTO People VALUES (36, 'Leonardo DiCaprio')
INSERT INTO People VALUES (37, 'Marco Beltrami')
INSERT INTO People VALUES (38, 'Mark Ruffalo')
INSERT INTO People VALUES (39, 'Mark Wahlberg')
INSERT INTO People VALUES (40, 'Martin Henderson')
INSERT INTO People VALUES (41, 'Martin Scorsese')
INSERT INTO People VALUES (42, 'Matt Damon')
INSERT INTO People VALUES (43, 'Millicent Simmonds')
INSERT INTO People VALUES (44, 'Miyu Irino')
INSERT INTO People VALUES (45, 'Naomi Watts')
INSERT INTO People VALUES (46, 'Noah Jupe')
INSERT INTO People VALUES (47, 'Park So-dam')
INSERT INTO People VALUES (48, 'Robert Downey Jr.')
INSERT INTO People VALUES (49, 'Rumi Hiiragi')
INSERT INTO People VALUES (50, 'Scarlett johansson')
INSERT INTO People VALUES (51, 'Scott Beck')
INSERT INTO People VALUES (52, 'Stephen McFeely')
INSERT INTO People VALUES (53, 'Suzanne Pleshette')
INSERT INTO People VALUES (54, 'Terry Gilliam')
INSERT INTO People VALUES (55, 'Terry Jones')
INSERT INTO People VALUES (56, 'William Monahan')
INSERT INTO People VALUES (57, 'Woo-sik Choi')

INSERT INTO Role VALUES (1, 'Actor')
INSERT INTO Role VALUES (2, 'Director')
INSERT INTO Role VALUES (3, 'Composer(Score)')
INSERT INTO Role VALUES (4, 'Writer')
INSERT INTO Role VALUES (5, 'Producer')
INSERT INTO Role VALUES (6, 'Actor and Writer')
INSERT INTO Role VALUES (7, 'Director and Writer')
INSERT INTO Role VALUES (8, 'Actor and Director') 

INSERT INTO MovieDetails VALUES (1,1,115,'2002/10/18',48000000,249348933, 'DreamWorks Pictures',2,8)
INSERT INTO MovieDetails VALUES (2,2,90,'2018/4/6', 21000000, 341000000, 'Paramount Pictures', 2, 8)
INSERT INTO MovieDetails VALUES(3,3,182, '2019/10/6', 356000000, 2797800564, 'Marvel Studios', 2,1)
INSERT INTO MovieDetails VALUES(4,4,92,'1975/4/27', 319000, 1940906, 'EMI Films', 1,3)
INSERT INTO MovieDetails VALUES(5,5,125, '2001/8/31', 19000000, 355475917, 'Toho', 1,7)
INSERT INTO MovieDetails VALUES(6,6,210,'1997/12/19', 200000000, 2195000000, 'Paramount Pictures', 2,10)
INSERT INTO MovieDetails VALUES(7,7,151,'2006/10/6', 90000000, 291500000, 'Warner Bros Pictures', 3,13)
INSERT INTO MovieDetails VALUES(8,8,132,'2019/10/30',15500000, 258000000, 'CJ Entertainment', 3,13)

INSERT INTO MoviePeople VALUES (1,3,3)
INSERT INTO MoviePeople VALUES (2,3,1)
INSERT INTO MoviePeople VALUES (3,3,2)
INSERT INTO MoviePeople VALUES (4,8,7)
INSERT INTO MoviePeople VALUES (5,3,1)
INSERT INTO MoviePeople VALUES (6,2,4)
INSERT INTO MoviePeople VALUES (7,3,1)
INSERT INTO MoviePeople VALUES (8,8,10)
INSERT INTO MoviePeople VALUES (9,3,1)
INSERT INTO MoviePeople VALUES (10,3,1)
INSERT INTO MoviePeople VALUES (11,3,4)
INSERT INTO MoviePeople VALUES (12,5,1)
INSERT INTO MoviePeople VALUES (13,1,1)
INSERT INTO MoviePeople VALUES (14,4,3)
INSERT INTO MoviePeople VALUES (15,3,1)
INSERT INTO MoviePeople VALUES (16,1,4)
INSERT INTO MoviePeople VALUES (17,3,1)
INSERT INTO MoviePeople VALUES (18,2,1)
INSERT INTO MoviePeople VALUES (19,4,1)
INSERT INTO MoviePeople VALUES (20,1,2)
INSERT INTO MoviePeople VALUES (21,4,6)
INSERT INTO MoviePeople VALUES (22,1,3)
INSERT INTO MoviePeople VALUES (23,5,7)
INSERT INTO MoviePeople VALUES (24,7,3)
INSERT INTO MoviePeople VALUES (25,7,1)
INSERT INTO MoviePeople VALUES (26,6,7)
INSERT INTO MoviePeople VALUES (27,6,3)
INSERT INTO MoviePeople VALUES (28,8,1)
INSERT INTO MoviePeople VALUES (29,3,1)
INSERT INTO MoviePeople VALUES (30,5,3)
INSERT INTO MoviePeople VALUES (31,3,2)
INSERT INTO MoviePeople VALUES (32,4,1)
INSERT INTO MoviePeople VALUES (33,2,8)
INSERT INTO MoviePeople VALUES (34,8,3)
INSERT INTO MoviePeople VALUES (35,6,1)
INSERT INTO MoviePeople VALUES (36,6,1)
INSERT INTO MoviePeople VALUES (36,7,1)
INSERT INTO MoviePeople VALUES (37,2,3)
INSERT INTO MoviePeople VALUES (38,3,1)
INSERT INTO MoviePeople VALUES (39,7,1)
INSERT INTO MoviePeople VALUES (40,1,1)
INSERT INTO MoviePeople VALUES (41,7,2)
INSERT INTO MoviePeople VALUES (42,7,1)
INSERT INTO MoviePeople VALUES (43,2,1)
INSERT INTO MoviePeople VALUES (44,5,1)
INSERT INTO MoviePeople VALUES (45,1,1)
INSERT INTO MoviePeople VALUES (46,2,1)
INSERT INTO MoviePeople VALUES (47,8,1)
INSERT INTO MoviePeople VALUES (48,3,1)
INSERT INTO MoviePeople VALUES (49,5,1)
INSERT INTO MoviePeople VALUES (50,3,1)
INSERT INTO MoviePeople VALUES (51,2,4)
INSERT INTO MoviePeople VALUES (52,3,4)
INSERT INTO MoviePeople VALUES (53,5,1)
INSERT INTO MoviePeople VALUES (54,4,8)
INSERT INTO MoviePeople VALUES (55,4,8)
INSERT INTO MoviePeople VALUES (56,7,4)
INSERT INTO MoviePeople VALUES (57,8,1) */


SELECT * FROM Role;


