USE MoviesDB;

ALTER TABLE MovieDetails WITH CHECK
ADD CONSTRAINT FK_ReviewID FOREIGN KEY (ReviewID) REFERENCES Reviews(ID)
ON UPDATE CASCADE
GO

ALTER TABLE MovieDetails WITH CHECK
ADD CONSTRAINT FK_RatingID FOREIGN KEY (RatingID) REFERENCES Rating(RatingID)
ON UPDATE CASCADE
GO

ALTER TABLE MovieDetails WITH CHECK
ADD CONSTRAINT FK_GenreID FOREIGN KEY (GenreID) REFERENCES Genre(GenreID)
ON UPDATE CASCADE
GO

ALTER TABLE MoviePeople WITH CHECK
ADD CONSTRAINT FK_PersonID FOREIGN KEY (PersonID) REFERENCES People(PersonID)
ON UPDATE CASCADE
GO

ALTER TABLE MoviePeople WITH CHECK
ADD CONSTRAINT FK_MovieID FOREIGN KEY (MovieID) REFERENCES MovieDetails(MovieID)
ON UPDATE CASCADE
GO

ALTER TABLE MoviePeople WITH CHECK
ADD CONSTRAINT FK_PrimaryFunction FOREIGN KEY (PrimaryFunction) REFERENCES Role(RoleID)
ON UPDATE CASCADE
GO